# Site settings
title: Cody Hutchens 
description: Cody hutchens's personal site
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "http://codyhutchens.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Cody Hutchens
user_description: A software engineer making his way through data science with an evolving passion for machine learning. My focus within the artifical intelligence space is shifting to reinforcement learning. I have worked on everything from building frontends to building backend apis to working on deep learning neural networks.
user_title: Lead Machine Learning Engineer
email: chutchens91@gmail.com
twitter_username: lorem_ipsum
github_username:  protomock
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-150437157-1"

exclude: ['package.json', 'src' , 'node_modules']
