import type { Experience, Education, Skill, SocialLinks } from '@/types';

export const siteConfig = {
  name: 'Cody Hutchens',
  title: 'Senior ML Engineer',
  tagline: 'Building intelligent systems. Advocating for data privacy. Watching too much anime.',
  jpTagline: '機械学習エンジニア',
  social: {
    linkedin: 'codyhutchens',
    instagram: 'cody.coder',
    github: 'chutch3',
    email: 'chutchens91@gmail.com',
    website: 'https://www.codyhutchens.com',
  } satisfies SocialLinks,
  resume: {
    url: 'https://drive.google.com/file/d/12vNYbanOX12RX-eF0EZohyb02Wyobmnx/view?usp=sharing',
  },
  skills: [
    { name: 'Python', category: 'languages' },
    { name: 'SQL', category: 'languages' },
    { name: 'Machine Learning', category: 'core' },
    { name: 'Tensorflow', category: 'core' },
    { name: 'Pytorch', category: 'core' },
    { name: 'Scikit-learn', category: 'core' },
    { name: 'Pandas', category: 'data' },
    { name: 'Numpy', category: 'data' },
    { name: 'BigQuery', category: 'data' },
    { name: 'PostGIS', category: 'data' },
    { name: 'Earth Engine', category: 'data' },
    { name: 'GCP', category: 'cloud' },
    { name: 'AWS', category: 'cloud' },
    { name: 'FastAPI', category: 'frameworks' },
    { name: 'Metaflow', category: 'frameworks' },
    { name: 'Docker', category: 'tools' },
    { name: 'Kubernetes', category: 'tools' },
    { name: 'Terraform', category: 'tools' },
    { name: 'Terragrunt', category: 'tools' },
    { name: 'Dagster', category: 'tools' },
    { name: 'Airflow', category: 'tools' },
    { name: 'Git', category: 'tools' },
    { name: 'Gitlab CI/CD', category: 'tools' },
    { name: 'Pytest', category: 'tools' },
  ] satisfies Skill[],
  experiences: [
    {
      company: 'Perennial',
      position: 'Senior Machine Learning Engineer',
      from: 'February 2023',
      to: 'Present',
      companyLink: 'https://www.perennial.earth/',
    },
    {
      company: 'Ontra',
      position: 'Senior Machine Learning Engineer',
      from: 'August 2022',
      to: 'February 2023',
      companyLink: 'https://www.ontra.ai/',
    },
    {
      company: 'Drizly',
      position: 'Senior Machine Learning Engineer',
      from: 'April 2022',
      to: 'June 2022',
      companyLink: 'https://drizly.com/',
    },
    {
      company: 'Drizly',
      position: 'Machine Learning Engineer',
      from: 'August 2021',
      to: 'April 2022',
      companyLink: 'https://drizly.com/',
    },
    {
      company: 'Humana',
      position: 'Lead Machine Learning Engineer',
      from: 'December 2019',
      to: 'August 2021',
      companyLink: 'https://www.humana.com/',
    },
    {
      company: 'Humana',
      position: 'Machine Learning Engineer',
      from: 'August 2018',
      to: 'December 2019',
      companyLink: 'https://www.humana.com/',
    },
    {
      company: 'Humana',
      position: 'Senior Software Engineer',
      from: 'January 2016',
      to: 'August 2018',
      companyLink: 'https://www.humana.com/',
    },
  ] satisfies Experience[],
  educations: [
    {
      institution: 'Georgia Institute of Technology',
      degree: 'Master of Science — Computer Science, Specialization in Machine Learning',
      from: '2018',
      to: '2021',
    },
    {
      institution: 'Indiana University Southeast',
      degree: 'Bachelor of Science — Computer Science',
      from: '2009',
      to: '2013',
    },
  ] satisfies Education[],
  googleAnalytics: {
    id: 'G-SPXQNC1QDT',
  },
};
