import type { Experience, Education, Skill, SocialLinks } from '@/types';

export const siteConfig = {
  name: 'Cody Hutchens',
  title: 'Senior ML Engineer',
  tagline:
    'Building intelligent systems. Advocating for data privacy. Watching too much anime.',
  jpTagline: '機械学習エンジニア',
  social: {
    linkedin: 'codyhutchens',
    github: 'chutch3',
    email: 'chutchens91@gmail.com',
    website: 'https://www.codyhutchens.com',
  } satisfies SocialLinks,
  resume: {
    url: 'https://drive.google.com/file/d/12vNYbanOX12RX-eF0EZohyb02Wyobmnx/view?usp=sharing',
  },
  skills: [
    { name: 'Python', category: 'languages' },
    { name: 'TypeScript', category: 'languages' },
    { name: 'SQL', category: 'languages' },
    { name: 'Machine Learning', category: 'core' },
    { name: 'LLMs', category: 'core' },
    { name: 'Agentic Systems', category: 'core' },
    { name: 'RAG', category: 'core' },
    { name: 'Tensorflow', category: 'core' },
    { name: 'Pytorch', category: 'core' },
    { name: 'XGBoost', category: 'core' },
    { name: 'LightGBM', category: 'core' },
    { name: 'Reinforcement Learning', category: 'core' },
    { name: 'Pandas', category: 'data' },
    { name: 'Numpy', category: 'data' },
    { name: 'BigQuery', category: 'data' },
    { name: 'PostGIS', category: 'data' },
    { name: 'Postgres', category: 'data' },
    { name: 'Redis', category: 'data' },
    { name: 'Earth Engine', category: 'data' },
    { name: 'Xarray', category: 'data' },
    { name: 'GCP', category: 'cloud' },
    { name: 'AWS', category: 'cloud' },
    { name: 'FastAPI', category: 'frameworks' },
    { name: 'Metaflow', category: 'frameworks' },
    { name: 'Flyte', category: 'frameworks' },
    { name: 'SQLAlchemy', category: 'frameworks' },
    { name: 'Docker', category: 'tools' },
    { name: 'Kubernetes', category: 'tools' },
    { name: 'Terraform', category: 'tools' },
    { name: 'Terragrunt', category: 'tools' },
    { name: 'Dagster', category: 'tools' },
    { name: 'Airflow', category: 'tools' },
    { name: 'Git', category: 'tools' },
    { name: 'GitHub Actions', category: 'tools' },
    { name: 'GitLab CI/CD', category: 'tools' },
    { name: 'Pytest', category: 'tools' },
    { name: 'Ansible', category: 'tools' },
  ] satisfies Skill[],
  goatcounter: {
    siteCode: 'chutch3-portfolio',
  },
  experiences: [
    {
      company: 'SmarterDx',
      position: 'Senior Machine Learning Engineer',
      from: 'July 2025',
      to: 'Present',
      companyLink: 'https://www.smarterdx.com/',
      stage: 'Unicorn',
      summary:
        'LLM-powered clinical AI for hospital revenue integrity and quality reporting.',
    },
    {
      company: 'Perennial',
      position: 'Senior Machine Learning Engineer II',
      from: 'February 2023',
      to: 'July 2025',
      companyLink: 'https://www.perennial.earth/',
      stage: 'Series A',
      summary:
        'Soil carbon estimation at global scale — feature engineering, distributed training, GCP infra.',
    },
    {
      company: 'Ontra',
      position: 'Senior Machine Learning Engineer',
      from: 'August 2022',
      to: 'February 2023',
      companyLink: 'https://www.ontra.ai/',
      stage: 'Series B',
      summary:
        'ML model gateway and async serving stack for legal document AI.',
    },
    {
      company: 'Drizly',
      position: 'Senior Machine Learning Engineer',
      from: 'August 2021',
      to: 'June 2022',
      companyLink: 'https://drizly.com/',
      stage: 'Acquired',
      summary:
        'Contextual multi-armed bandit for shelf optimization and conversion.',
    },
    {
      company: 'Humana',
      position: 'Lead Machine Learning Engineer',
      from: 'November 2012',
      to: 'August 2021',
      companyLink: 'https://www.humana.com/',
      stage: 'Fortune 50',
      summary:
        'Deep learning for cost transparency, experimentation platform, TensorFlow in production.',
    },
  ] satisfies Experience[],
  educations: [
    {
      institution: 'Georgia Institute of Technology',
      degree:
        'Master of Science — Computer Science, Specialization in Machine Learning',
      from: '2018',
      to: '2021',
    },
    {
      institution: 'Indiana University Southeast',
      degree: 'Bachelor of Science — Computer Science, Information Systems',
      from: '2009',
      to: '2013',
    },
  ] satisfies Education[],
};
